USE [master]
GO
CREATE LOGIN [DENBYGROUP\G Xstore SQL Admins] FROM WINDOWS WITH DEFAULT_DATABASE=[master]
GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [DENBYGROUP\G Xstore SQL Admins]
GO
USE [xstore]
GO
CREATE USER [DENBYGROUP\G Xstore SQL Admins] FOR LOGIN [DENBYGROUP\G Xstore SQL Admins]
GO
USE [xstore]
GO
ALTER ROLE [db_owner] ADD MEMBER [DENBYGROUP\G Xstore SQL Admins]
GO